name: test

on:
  push:

jobs:
  build-image:
    if: "!startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/heads/master')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker  image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
